
DROP TABLE IF EXISTS teacher_classes;
DROP TABLE IF EXISTS classes;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS roles;
DROP INDEX IF EXISTS idx_users_school_id;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS schools;