name: school_manager
services:
  server:
    image: ftyszyx752/school_manager:latest
    env_file:
      - .env
    ports:
      - "${LISTEN_OUT_PORT}:${LISTEN_PORT}"
    volumes:
      - ./deploy/server/logs:/app/logs
    restart: unless-stopped
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true