//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "classes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub grade: i32,
    pub class: i32,
    pub school_id: i32,
    pub status: i32,
    pub password: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::schools::Entity",
        from = "Column::SchoolId",
        to = "super::schools::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Schools,
    #[sea_orm(has_many = "super::teacher_classes::Entity")]
    TeacherClasses,
}

impl Related<super::schools::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Schools.def()
    }
}

impl Related<super::teacher_classes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeacherClasses.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::teacher_classes::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::teacher_classes::Relation::Classes.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
