//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub mod prelude;

pub mod classes;
pub mod permissions;
pub mod role_permissions;
pub mod roles;
pub mod schools;
pub mod teacher_classes;
pub mod user_roles;
pub mod users;
