//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::classes::Entity as Classes;
pub use super::permissions::Entity as Permissions;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::schools::Entity as Schools;
pub use super::teacher_classes::Entity as TeacherClasses;
pub use super::user_roles::Entity as UserRoles;
pub use super::users::Entity as Users;
